### ISSUE TITLE
[ENHANCEMENT] Refactor code

### ISSUE THREAD

**Issue by ElBe-Plaq** [ElBe-Development/discord.py-bot-template#46]
Refactor your code to be readable and usable.

**Links**
YouTube Videos about this: https://www.youtube.com/watch?v=-J3wNP6u5YU, https://www.youtube.com/watch?v=qUeud6DvOWI and more
Websites: https://peps.python.org and more

**Todos**
- [ ] Rename...
   - [ ] Variables
   - [ ] Constants
   - [ ] Functions
   - [ ] Abbreviations
- [ ] Use f strings
- [ ] Refactor `functions.py` (`utils` folder?)
- [ ] Refactor `config.json`
- [ ] Refactor other code
- [ ] Sort imports
- [ ] Sort variables
- [ ] Assign types to variables
- [ ] Assign errors to `except`
- [ ] Change base error class to subclass of `BaseException` or `Exception`
- [ ] Clean up GitHub
- [ ] Remove unnecessary requirements

More coming as an edit

**Comment by ElBe-Plaq** [comment]
Why am I doing this?

**Comment by ElBe-Plaq** [comment]
Basically it's a rewrite

**Comment by ElBe-Plaq** [comment]
Maybe I'll use `rich` later on too.

**Comment by ElBe-Plaq** [comment]
#$(COLOR)
#$(LEVELNAME)
#$(MESSAGE)
#$(NAME)
#$(TIMESTAMP)

**Comment by ElBe-Plaq** [comment]
I'll work on this again.

**Comment by ElBe-Plaq** [comment]
I'll completley rewrite the entire cog system.
